### ISSUE TITLE
Possibility to run this as Coreboot payload

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [io12/BootMine#1]
As far as I can see, this uses no BIOS routines at all.
Could this run as Coreboot payload?

Would be fun to port, even if just for educational purposes.

**Comment by io12** [comment]
Yes, it's definitely possible with some amount of porting. The only interrupts BootMine uses are 0x10 (for printing strings and changing the graphics mode) and 0x16 (for getting keystrokes). I'm not sure if these are provided for Coreboot payloads, but if they aren't, the interrupt calls can be replaced with the lower-level operations that the interrupts do internally (probably communicating with IO ports) or be replaced with Coreboot routines.

I couldn't easily find details on the execution environment of Coreboot payloads, but it seems like they're 32-bit, ELF files, and relocatable (I could be wrong about this). This seems different from a boot sector or COM file's execution environment, although it's possible that Coreboot has more options for 16-bit flat binaries with a static load address.
