### ISSUE TITLE
Invalid partition table

### ISSUE THREAD

**Issue by ABotond** [io12/BootMine#2]
Hi,

thanks a lot this project, it is very important.

However, after I tried to install it on my Dell Notebooks main HDD, I've got "Invalid partition table" error on boot from this hard disk.
I've enabled the legacy boot.
I've tried dd if=bootmine.img of=/dev/sda from a live USB, but after the above error I also tried to create a partition with fdisk, and I've installed it to /dev/sda1 as well - still the same problem.

Do you have any idea what the problem could be?

**Comment by io12** [comment]
I found this thread. https://www.dell.com/community/Laptops-General-Read-Only/Invalid-partition-table/td-p/3987537

**Comment by ABotond** [comment]
Hi,

thank you for the prompt response!
Although the thread wasn't really helpful, it made me retry it again.
It turned out, that pressing any key (besides ctrl+alt+del) makes actually the BIOS start the boot sequence, and starts this great application.

Thus, I think, the issue can be closed.
